### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by chinnakrishna7802** [RahulSabinkar/organ-donation-platform#1]
![Screenshot (18)](https://github.com/RahulSabinkar/organ-donation-platform/assets/124236858/8b9d778a-9eb4-4ad9-890c-75278992d505)

**Comment by RahulSabinkar** [comment]
@chinnakrishna7802 Hey. Nice of you to open an issue here, I have known about this issue for quite a while. It's arising because the webpack version is quite old, as are all the other packages. I'll be honest with you, this was my very first project I developed along with a close friend of mine for practice and haven't touched it for almost a year.  I currently don't have plans of fixing it but you're welcome to release a PR or create your own fork. Good day!

**Comment by Shreyashk-07** [comment]
"set NODE_OPTIONS=--openssl-legacy-provider" use this command if you are using windows. It worked for me.
